### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mwk20** [edwardcunningham/spritz#1]
Please can you clarify the licence for this repo/code?

**Comment by AaronGoldman** [comment]
once there is a licence 
I would recommend
    https://opensource.org/licenses/Apache-2.0 or
    https://opensource.org/licenses/MIT

we should add
    EncryptWithIV(K,IV , M )
    DomHash(J , M , r )
    MAC(K, M , r )
    AEAD(K, Z, H , M , r )
    DRBG(r)

also warn user away from Encrypt(K, M ) which should never be used with the same key twice the IV is important
